services:
  acquirer_app:
    container_name: acquirer_app
    working_dir: /acquirer_app
    image: ruby:3.2
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bundle exec rails s -p 3007 -b '0.0.0.0'"
    volumes:
      - .:/acquirer_app
      - acquirer_gems:/usr/local/bundle
    ports:
      - "3007:3007"
    depends_on:
      - acquirer_db
    networks:
      - policy-network
  acquirer_db:
    container_name: acquirer_db
    image: postgres:16
    volumes:
      - acquirer_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      # POSTGRES_PORT: 5435
    ports:
      - "5435:5432"
    networks:
      - policy-network

volumes:
  acquirer_db:
  acquirer_gems:

networks:
  policy-network:
    name: policy_network
    external: true
