services:
  acquirer_app:
    container_name: acquirer_app
    working_dir: /acquirer_app
    image: ruby:3.2
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bundle exec rails s -p 3007 -b '0.0.0.0'"
    volumes:
      - .:/acquirer_app
      - rubygems:/usr/local/bundle
    ports:
      - "3007:3007"
    depends_on:
      - postgres
    networks:
      - policy-network
  postgres:
    hostname: acquirer_db
    image: postgres:16
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - policy-network

volumes:
  database:
  rubygems:

networks:
  policy-network:
    name: policy_network
    external: true
